name: Java WAR Deploy to Azure Web App
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  JAVA_VERSION: '8'
  TOMCAT_VERSION: '8.5'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Debug Directory Structure
        run: |
          pwd
          ls -la
          find . -type d

      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: '8'
          distribution: 'temurin'
          cache: maven

      - name: Debug Environment Variable
        run: |
          echo "APP_SERVICE_PLAN is set to: $APP_SERVICE_PLAN"
        env:
          APP_SERVICE_PLAN: ${{ secrets.APP_SERVICE_PLAN }}

      - name: Build with Maven
        run: mvn clean package -X
        env:
          APP_SERVICE_PLAN: ${{ secrets.APP_SERVICE_PLAN }}

      - name: Check WAR contents
        run: |
          cd target
          jar tvf ROOT.war | grep index.html
          unzip -p ROOT.war index.html

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: web-app-tomcat-neu
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_A5887968C7E04367A4F22E983212BEDB }}
          package: target/*.war